default-resources:
  - disk_mb=4096
  - mem_mb=16096
  - time=120
  - gpus=0
rerun-incomplete: True
rerun-triggers: mtime 
restart-times: 2
printshellcmds: True
reason: True
use-conda: True
show-failed-logs: True 